### ISSUE TITLE
Responsive image

### ISSUE THREAD

**Issue by ahmadihamid** [tbiering/hugo-slider-shortcode#17]
how to make this slider responsive?

**Comment by tbiering** [comment]
Hey @ahmadihamid ,

sorry for the late response. At the moment, the slider is designed to be used with fixed width/height images as the content of the slider. This is because the calculation of the slide-movement is currently using the width of the slider-display as the delta (see `function moveCss(nextSlideId)`).

Unfortunately, I moved away from hugo for my current projects, thus I current don't plan on making this change myself. I would absolutely welcome a PR for the change!

Best regards,
Thomas
